import "./styles/globals.css";
import type { Metadata } from "next";
import { Providers } from '@components/common/Providers';
import Header from '@components/common/Header';
import Footer from '@components/common/Footer';

import { Inter } from 'next/font/google';


const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Pokédex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.variable} antialiased bg-white text-gray-900 h-full`}>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
